services:
  back:
    build: ./back
    container_name: project_back
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
      - ./back/media:/app/media
      - /app/.venv
      - /app/db.sqlite3
    depends_on:
      - db
      
    networks:
      - project_network

  front:
    build: ./front
    container_name: project_front
    extra_hosts:
      - "localhost:host-gateway"
    ports:
      - "5173:3000"
    depends_on:
      - back
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  postgres_data:
