services:
  back:
    build: ./back
    healthcheck:
      test: curl -sS http://127.0.0.1:8000/
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1s
    container_name: project_back
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
      - /app/database
      - /app/.venv
      
    networks:
      - project_network

  front:
    build: ./front
    container_name: project_front
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      back:
        condition: service_healthy
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

