# Generated by Django 6.0.5 on 2026-06-07 20:32

import api.models
import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="tests",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=[],
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list, (api.models.Test,)
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="completed_modules",
            field=models.ManyToManyField(blank=True, to="api.module"),
        ),
        migrations.AlterField(
            model_name="user",
            name="completed_topics",
            field=models.ManyToManyField(blank=True, to="api.topic"),
        ),
        migrations.AlterField(
            model_name="user",
            name="info",
            field=models.TextField(blank=True, default=""),
        ),
    ]
