# Generated by Django 6.0.5 on 2026-06-04 20:47

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_history",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list, (str,)
                ),
            ),
        ),
    ]
