# Generated by Django 6.0.5 on 2026-06-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_user_chat_history_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="dependencies",
            field=models.ManyToManyField(to="api.module"),
        ),
    ]
