# Generated by Django 6.0.5 on 2026-06-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_module_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="completed_modules",
            field=models.ManyToManyField(to="api.module"),
        ),
        migrations.AddField(
            model_name="user",
            name="completed_sections",
            field=models.ManyToManyField(to="api.modulesection"),
        ),
    ]
