
run *args:
    pnpm run dev {{args}}

gen *args:
    rm -rf app/client
    pnpm run generate:api {{args}}

run-all:
     tmux new-session -d 'just run --host' \; new-window 'cd ../back && direnv exec . just'

